server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}

  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        dialect: ${DATABASE_DIALECT}
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update

cors:
  allowed_origins: ${LIST_OF_ORIGINS}
  allowed_methods: ${LIST_OF_METHODS}
  allowed_headers: ${LIST_OF_HEADERS}
  pattern: ${CORS_PATTERN}

jwt:
  secret: ${JWT_SECRET}
  duration: ${JWT_DURATION}