server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/test
  messages:
    basename: lang
    use-code-as-default-message: true
    encoding: UTF-8

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create